platform:
  - Win32

os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  PYTHON: "C:\\Python35"

build_script:
  - cmd: >-
      git submodule update --init --recursive

      SET PATH=%PATH%;%PYTHON%\Scripts\

      python ci.py clean

      python ci.py deps

      python ci.py windows build-all
