platform:
  - Win32

os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  PYTHON: "C:\\Python36"

build_script:
  - cmd: >-
      git submodule update --init --recursive

      SET PATH=%PATH%;%PYTHON%\Scripts\

      SET LP3_ROOT_PATH=%CD%\standalone\media

      pip install cget

      set OLD_PATH=%PATH%

      mkdir debug

      cd debug

      cget init -DCMAKE_GENERATOR_PLATFORM:none=x64 -DCMAKE_BUILD_TYPE:none=Debug

      set PATH=%CD%\cget\lib;%OLD_PATH%

      cget install catchorg/Catch2@v1.11.0 --define NO_SELFTEST=True

      cget install Microsoft/GSL@1c95f9436eae69c9b9315911ef6aa210df7d1e31 -X header

      cget install g-truc/glm@0.9.8.5

      cget install TimSimpson/download-sdl2 --debug

      cmake -DCMAKE_TOOLCHAIN_FILE=./cget/cget/cget.cmake -H../standalone -B./

      cmake --build ./ --config Debug

      ctest --output-on-failure

      cd ..

      mkdir release

      cd release

      cget init -DCMAKE_GENERATOR_PLATFORM:none=x64 -DCMAKE_BUILD_TYPE:none=Release

      set PATH=%CD%\cget\lib;%OLD_PATH%

      cget install -f ../requirements.txt --release

      cmake -DCMAKE_TOOLCHAIN_FILE=./cget/cget/cget.cmake -H../standalone -B./

      cmake --build ./ --config Release

      ctest --output-on-failure
