platform:
  - Win32

os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  PYTHON: "C:\\Python36"

build_script:
  - cmd: >-
      git submodule update --init --recursive

      SET PATH=%PATH%;%PYTHON%\Scripts\

      curl -fsSL -o cenv.zip https://github.com/TimSimpson/cenv/archive/master.zip

      7z x cenv.zip

      cd cenv-master

      CALL install.bat

      SET PATH=%CD%\output\wvenv\Scripts;%PATH%

      cenv init win64-debug -DCMAKE_GENERATOR_PLATFORM:none=x64 -DCMAKE_BUILD_TYPE:none=Debug

      cenv init win64-release -DCMAKE_GENERATOR_PLATFORM:none=x64 -DCMAKE_BUILD_TYPE:none=Release

      cenv set win64-debug

      cget install -f ../requirements.txt --debug

      mkdir build-debug && cd build-debug

      cmake -G "Visual Studio 15 2017 Win64" -H../standalone -B./

      cmake --build ./ --config debug

      cd ..

      cenv set win64-release

      cget install -f ../requirements.txt --release

      mkdir build-release && cd build-release

      cmake -G "Visual Studio 15 2017 Win64" -H../standalone -B./

      cmake --build ./ --config release
