os: Visual Studio 2019

environment:
    PYTHON: "C:\Python37"

    matrix:

        - PROFILE:  msvc-d-shared
        - PROFILE:  msvc-r-static

install:
  - git clone https://github.com/TimSimpson/ci-land.git ci
  - cd ci
  - git checkout 648c79f036e5b302349404315430fc4aee26996a
  - cd ..
  - ci\cpp\conan\appveyor\install.bat

build_script:
  - git submodule update --init --recursive
  - ci\cpp\conan\appveyor\run.bat %PROFILE%
