
language: cpp

compiler:
  - gcc

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-6
      - g++-6
      - clang-3.8
      - clang-format-3.8
      - clang-tidy-3.8
      - libstdc++6
      - ninja-build
      - libboost-dev
      - libsdl2-dev
      - libsdl2-image-dev
env: COMPILER=g++-6


install:
  - |
    pushd /tmp
    travis_retry wget --quiet --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.0-rc2-Linux-x86_64.tar.gz
    tar -xf cmake-3.8.0-rc2-Linux-x86_64.tar.gz
    popd

script:
  - |
    export PATH=/tmp/cmake-3.8.0-rc2-Linux-x86_64/bin:${PATH}
    cmake --version
    python ci.py travis
